[package]
name = "lattice"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sha3 = "0.10"
rand_distr = "0.4"
ndarray = "0.16.1"
num = "0.4.3"
ndarray-linalg = "0.16.0" # Or the latest version
